#ifndef SPO_FPOINT_H_HEADER_INCLUDED_B9A122DF
#define SPO_FPOINT_H_HEADER_INCLUDED_B9A122DF

#include "SPo_TplPoint.h"
//##ModelId=465ED138000F
typedef SPo_TplPoint<float> SPo_FPoint;



#endif /* SPO_FPOINT_H_HEADER_INCLUDED_B9A122DF */
